spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/rent-now
  datasource:
    url: jdbc:mysql://localhost:3306/rent-now-database
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
server:
  servlet:
    context-path: /api
  tomcat:
    accesslog:
      enabled: true